// This file declares the gRPC service and messages
// for controlling the music player.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: player.proto

package player

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *string                `protobuf:"bytes,1,opt,name=command,proto3,oneof" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRequest) Reset() {
	*x = PlayerRequest{}
	mi := &file_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRequest) ProtoMessage() {}

func (x *PlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRequest.ProtoReflect.Descriptor instead.
func (*PlayerRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerRequest) GetCommand() string {
	if x != nil && x.Command != nil {
		return *x.Command
	}
	return ""
}

type PlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *string                `protobuf:"bytes,1,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerResponse) Reset() {
	*x = PlayerResponse{}
	mi := &file_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerResponse) ProtoMessage() {}

func (x *PlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerResponse.ProtoReflect.Descriptor instead.
func (*PlayerResponse) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_player_proto protoreflect.FileDescriptor

const file_player_proto_rawDesc = "" +
	"\n" +
	"\fplayer.proto\x12\fmusic.player\":\n" +
	"\rPlayerRequest\x12\x1d\n" +
	"\acommand\x18\x01 \x01(\tH\x00R\acommand\x88\x01\x01B\n" +
	"\n" +
	"\b_command\";\n" +
	"\x0ePlayerResponse\x12\x1d\n" +
	"\amessage\x18\x01 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message2\xa4\x03\n" +
	"\x06Player\x12F\n" +
	"\tGetStatus\x12\x1b.music.player.PlayerRequest\x1a\x1c.music.player.PlayerResponse\x12A\n" +
	"\x04Play\x12\x1b.music.player.PlayerRequest\x1a\x1c.music.player.PlayerResponse\x12B\n" +
	"\x05Pause\x12\x1b.music.player.PlayerRequest\x1a\x1c.music.player.PlayerResponse\x12A\n" +
	"\x04Stop\x12\x1b.music.player.PlayerRequest\x1a\x1c.music.player.PlayerResponse\x12A\n" +
	"\x04Next\x12\x1b.music.player.PlayerRequest\x1a\x1c.music.player.PlayerResponse\x12E\n" +
	"\bPrevious\x12\x1b.music.player.PlayerRequest\x1a\x1c.music.player.PlayerResponseB,Z*google.golang.org/grpc/music/player;playerb\x06proto3"

var (
	file_player_proto_rawDescOnce sync.Once
	file_player_proto_rawDescData []byte
)

func file_player_proto_rawDescGZIP() []byte {
	file_player_proto_rawDescOnce.Do(func() {
		file_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)))
	})
	return file_player_proto_rawDescData
}

var file_player_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_player_proto_goTypes = []any{
	(*PlayerRequest)(nil),  // 0: music.player.PlayerRequest
	(*PlayerResponse)(nil), // 1: music.player.PlayerResponse
}
var file_player_proto_depIdxs = []int32{
	0, // 0: music.player.Player.GetStatus:input_type -> music.player.PlayerRequest
	0, // 1: music.player.Player.Play:input_type -> music.player.PlayerRequest
	0, // 2: music.player.Player.Pause:input_type -> music.player.PlayerRequest
	0, // 3: music.player.Player.Stop:input_type -> music.player.PlayerRequest
	0, // 4: music.player.Player.Next:input_type -> music.player.PlayerRequest
	0, // 5: music.player.Player.Previous:input_type -> music.player.PlayerRequest
	1, // 6: music.player.Player.GetStatus:output_type -> music.player.PlayerResponse
	1, // 7: music.player.Player.Play:output_type -> music.player.PlayerResponse
	1, // 8: music.player.Player.Pause:output_type -> music.player.PlayerResponse
	1, // 9: music.player.Player.Stop:output_type -> music.player.PlayerResponse
	1, // 10: music.player.Player.Next:output_type -> music.player.PlayerResponse
	1, // 11: music.player.Player.Previous:output_type -> music.player.PlayerResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_player_proto_init() }
func file_player_proto_init() {
	if File_player_proto != nil {
		return
	}
	file_player_proto_msgTypes[0].OneofWrappers = []any{}
	file_player_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_player_proto_goTypes,
		DependencyIndexes: file_player_proto_depIdxs,
		MessageInfos:      file_player_proto_msgTypes,
	}.Build()
	File_player_proto = out.File
	file_player_proto_goTypes = nil
	file_player_proto_depIdxs = nil
}
