services:
  mpv:
    build: ./mpv-backend/
    volumes:
      - mpvsocket:/tmp
    devices:
      - /dev/sr0:/dev/sr0
    environment:
      - CD_DEVICE=/dev/sr0
      - MPV_SOCKET=/tmp/mpvsocket

  player-tui:
    build: ./go-tui-client/
    volumes:
      - mpvsocket:/tmp
    depends_on:
      - mpv
    environment:
      - MPV_SOCKET=/tmp/mpvsocket

volumes:
  mpvsocket:
